version: "3.9"

services:
  web:
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      db:
        condition: service_healthy
    environment:
      - WORDPRESS_URL=localhost
      - WORDPRESS_ADMIN_USER
      - WORDPRESS_ADMIN_PASSWORD=wordpress #If you want to use the random generated password, just remove this line
      - WORDPRESS_ADMIN_EMAIL=test@local.host
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
#      - WORDPRESS_DEBUG=true
    ports:
      - "80:80"
    volumes:
      - ./wp-content:/mnt/data
  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=wordpress
      - MARIADB_USER=wordpress
      - MARIADB_PASSWORD=wordpress
      - MARIADB_DATABASE=wordpress
    volumes:
      - ./db-data:/var/lib/mysql
    healthcheck:
      test: mysqladmin -uwordpress -pwordpress ping -h localhost
      timeout: 3s
      retries: 10