version: "3.9"

services:
  web:
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      db:
        condition: service_healthy
    environment:
      - WORDPRESS_URL
      - WORDPRESS_ADMIN_USER
      - WORDPRESS_ADMIN_PASSWORD=wordpress #If you want to use the random generated password, just remove this line
      - WORDPRESS_ADMIN_EMAIL
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_NAME
      - WORDPRESS_DB_PASSWORD
      - WORDPRESS_DEBUG=true
    ports:
      - "80:80"
    volumes:
      - ./wp-content:/var/www/wp-content
  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=wordpress
      - MARIADB_DATABASE=wordpress
    healthcheck:
      test: ["CMD", "mysqladmin", "-u", "root", "-p$$MARIADB_ROOT_PASSWORD", "ping"]
      timeout: 3s
      retries: 10